# Generated by Django 2.0.4 on 2019-08-21 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_endorsement_endorsemententry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='paper',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='endorsemententry',
            name='paper',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='endorsemententry',
            unique_together={('paper', 'user')},
        ),
    ]
