# Generated by Django 2.2.5 on 2019-09-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_endorsement_endorsemententry_flaggedcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedcomment',
            name='violation',
            field=models.CharField(max_length=100),
        ),
    ]
