# Generated by Django 2.0.4 on 2019-08-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190821_2235'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endorsemententry',
            unique_together=set(),
        ),
    ]
