# Generated by Django 2.0.4 on 2019-08-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190821_1354'),
        ('catalog', '0005_auto_20190821_2237'),
    ]

    operations = [
    ]
