# Generated by Django 2.0.4 on 2019-09-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_merge_20190828_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endorsement',
        ),
        migrations.RenameField(
            model_name='endorsemententry',
            old_name='paper',
            new_name='paper_id',
        ),
    ]
