# Generated by Django 2.2.5 on 2019-09-27 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_merge_20190828_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('violation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comment flag',
                'ordering': ['violation', '-created_at'],
            },
        ),
    ]
