# Generated by Django 2.0.4 on 2019-09-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190916_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsemententry',
            name='paper_title',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
    ]
