# Generated by Django 2.2.5 on 2019-09-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_endorsemententry_paper_title'),
        ('catalog', '0007_flaggedcomment'),
    ]

    operations = [
    ]
