# Generated by Django 2.2.5 on 2019-10-17 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0010_auto_20191015_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentflag',
            name='proposed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HiddenComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hidden flag',
                'ordering': ['proposed_by', 'comment_id'],
            },
        ),
    ]
